# Generated by Django 2.1.8 on 2019-08-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190804_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.TextField(blank=True, choices=[('m', '남성'), ('f', '여성')], max_length=10),
        ),
    ]
