# Generated by Django 2.1.8 on 2019-08-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190804_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
