# Generated by Django 2.1.8 on 2019-07-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='selfqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('question', models.CharField(max_length=500, null=True)),
                ('answer', models.CharField(max_length=500, null=True)),
                ('pub_date', models.DateField(null=True, verbose_name='date published')),
            ],
        ),
    ]
