# Generated by Django 2.2 on 2019-07-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqa',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='질문 제목'),
        ),
        migrations.AlterField(
            model_name='userqa',
            name='question',
            field=models.CharField(max_length=100, verbose_name='내용'),
        ),
    ]
