# Generated by Django 2.2 on 2019-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0004_auto_20190728_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqa',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
