# Generated by Django 2.2 on 2019-07-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0005_userqa_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userqa',
            name='a_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
