# Generated by Django 2.2 on 2019-07-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0007_answerqa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userqa',
            name='a_title',
        ),
        migrations.RemoveField(
            model_name='userqa',
            name='answer',
        ),
    ]
