# Generated by Django 2.2 on 2019-07-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0008_auto_20190729_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerqa',
            name='author',
        ),
    ]
